### ISSUE TITLE
Formulario de cadastro de aluno com bootstrap

### ISSUE THREAD

**Issue by bmarchete** [lolrafael123/git-emib#2]
Olá sr @lolrafael123 , vamos criar um form para cadastrar aluno com bootstrap. Fico aguardando voce criar uma página html com o formulario apenas. Eu vou baixar os arquivos do bootstrap e depois finalizo a página.

**Comment by lolrafael123** [comment]
:+1:

**Comment by lolrafael123** [comment]
criado formulário no commit: ad2d44f8fa9849f2ab2f930c7baaf7bda26651b4
